spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_read?serverTimezone=UTC
    username: root
    password: root
  mvc:
    view:
      prefix: /templates
      suffix: .html
  redis:
    host: 192.168.56.101
    port: 6379
    password:
    database: 0

#redis的连接池的设置
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.duing.model
  mapper-locations: classpath:mapper/*.xml

